/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nirinfo.gestion.stock;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDI
 */
public class ProductFenetre extends javax.swing.JFrame {

    private Connexion connexion;
    private Connection con;
    private int selectedId = 0;

    /**
     * Creates new form ProductFenetre
     */
    public ProductFenetre() {
        initComponents();
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        connexion = new Connexion();
        con = connexion.getCon();
        affiche();
    }

    public void affiche() {
        table.setModel(new javax.swing.table.DefaultTableModel(
                tabListe(),
                new String[]{
                    "id", "Ref", "Designation", "Prix Unitaire", "Stock"
                }
        ));
    }

    String[][] tabListe() {
        String[][] liste = new String[this.getNumberRow()][5];
        try {
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery("SELECT * FROM produit");
            int i = 0;
            while (rs.next()) {
                liste[i][0] = rs.getString("idProd");
                liste[i][1] = rs.getString("ref");
                liste[i][2] = rs.getString("designation");
                liste[i][3] = rs.getString("pu");
                liste[i][4] = rs.getString("stock");
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FournisseurFenetre.class.getName()).log(Level.SEVERE, null, ex);
        }

        return liste;
    }

    int getNumberRow() {
        int n = 0;
        try {
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery("SELECT * FROM produit");
            while (rs.next()) {
                n++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FournisseurFenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
        return n;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        reference = new javax.swing.JTextField();
        desig = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Produit");

        jLabel1.setText("Ref");

        reference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceActionPerformed(evt);
            }
        });

        jLabel3.setText("Designation");

        jLabel4.setText("Prix Unitaire");

        jLabel5.setText("Stock");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Ref", "Designation", "Prix Unitaire", "Stock"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        btnUpdate.setText("Modifier");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        delete.setText("Supprimer");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        jButton4.setText("Ajouter");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(desig, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(172, 172, 172))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addGap(13, 13, 13)
                        .addComponent(jButton4))
                    .addComponent(pu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115)
                        .addComponent(reference, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(reference, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(desig, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void referenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceActionPerformed

    public void insert(Product product) {
        try {
            PreparedStatement pst = con.prepareStatement("INSERT INTO produit (ref, designation, pu,stock) VALUE (?,?,?,?)");
            pst.setString(1, product.getRef());
            pst.setString(2, product.getDesignation());
            pst.setInt(3, product.getPu());
            pst.setInt(4, product.getStock());
            pst.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(FournisseurFenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String ref = reference.getText();
        String designation = desig.getText();
        String price = pu.getText();
        String st = stock.getText();

        try {
            PreparedStatement pst = con.prepareStatement("SELECT * FROM produit WHERE ref=?");
            pst.setString(1, ref);
            ResultSet rs = pst.executeQuery();

            if (ref.isEmpty() || designation.isEmpty() || price.isEmpty() || st.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !!");

            } else if (rs.next()) {
                JOptionPane.showMessageDialog(this, "La ref existe déja");
                reference.setText("");
            } else {
                Product produit = new Product();
                produit.setRef(ref);
                produit.setDesignation(designation);
                produit.setUp(Integer.valueOf(price));
                produit.setStock((Integer.valueOf(st)));

                insert(produit);
                affiche();
                reference.setText("");
                desig.setText("");
                pu.setText("");
                stock.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Une erreur c'est produit" + e.getMessage());
        }
    }//GEN-LAST:event_jButton4MouseClicked

    public void update(Product po) {
        try {
            PreparedStatement pst = con.prepareStatement("UPDATE produit set ref=?, designation=?, pu=?, stock=? WHERE idProd=?");
            pst.setString(1, po.getRef());
            pst.setString(2, po.getDesignation());
            pst.setInt(3, po.getPu());
            pst.setInt(4, po.getStock());
            pst.setInt(5, po.getId());
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(InfoFournisseurFenetre.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur lors de la mise à jour : " + ex.getMessage());
        }
    }

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        String ref = reference.getText();
        String designation = desig.getText();
        String price = pu.getText();
        String st = stock.getText();

        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne dans la table.");
            return;
        }
        Product produit = this.getId(selectedId);

        if (ref.isEmpty() || designation.isEmpty() || price.isEmpty() || st.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !!");

        } else if (produit != null) {
            produit.setRef(reference.getText());
            produit.setDesignation(desig.getText());
            produit.setUp(Integer.valueOf(pu.getText()));
            produit.setStock(Integer.valueOf(stock.getText()));
            update(produit);
            affiche();
            reference.setText("");
            desig.setText("");
            pu.setText("");
            stock.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne dans la table.");
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    public Product getId(int id) {
        try {
            PreparedStatement pst = con.prepareCall("SELECT * FROM produit WHERE idProd=?");
            pst.setInt(1, id);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                return new Product(
                        rs.getInt("idProd"),
                        rs.getString("ref"),
                        rs.getString("designation"),
                        rs.getInt("pu"),
                        rs.getInt("stock")
                );
            }
        } catch (SQLException ex) {
            Logger.getLogger(FournisseurFenetre.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int ligne = table.getSelectedRow();
        if (ligne >= 0) {
            selectedId = Integer.parseInt(table.getValueAt(ligne, 0).toString());
        }
        Product produit = this.getId(selectedId);
        if (produit != null) {
            reference.setText(produit.getRef());
            desig.setText(produit.getDesignation());
            pu.setText(String.valueOf(produit.getPu()));
            stock.setText(String.valueOf(produit.getStock()));
        }
    }//GEN-LAST:event_tableMouseClicked

    public void delete(int id) {
        try {
            PreparedStatement pst = con.prepareStatement("DELETE FROM produit WHERE idProd=?");
            pst.setInt(1, id);

            pst.executeUpdate();
        } catch (Exception e) {
        }
    }

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne dans la table.");
            return;
        }
        Product produit = this.getId(selectedId);
        if (produit != null) {
            delete(produit.getId());
            affiche();
            reference.setText("");
            desig.setText("");
            pu.setText("");
            stock.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne dans la table.");
            return;

        }

    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductFenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductFenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton delete;
    private javax.swing.JTextField desig;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pu;
    private javax.swing.JTextField reference;
    private javax.swing.JTextField stock;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
